require 'typescript/rails'
require 'typescript/rails/railtie'
require 'typescript/rails/engine'
require 'typescript/rails/template'
require 'typescript/rails/template_handler'
require 'typescript/rails/transformer'
require 'typescript/rails/version'
